version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - nestjs
    depends_on:
      - mysql
    command: ["yarn", "start:dev"]
  mysql:
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
        - ./mysql-scripts:/docker-entrypoint-initdb.d
        - ./mysql:/var/lib/mysql
    networks:
      - nestjs
networks:
  nestjs:
